development:
  adapter: sqlite3
  database: db/wsdls.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: db/wsdls.sqlite3
  timeout: 5000
