# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "wsdls", :force => true do |t|
    t.column "name",        :string
    t.column "contents",    :text
    t.column "host",        :string
    t.column "application", :string
  end

  create_table "wsdls_xsds", :id => false, :force => true do |t|
    t.column "xsd_id",  :integer
    t.column "wsdl_id", :integer
  end

  create_table "xsds", :force => true do |t|
    t.column "name",     :string
    t.column "contents", :text
  end

end
